### ISSUE TITLE
Can't replicate tutorial's example

### ISSUE THREAD

**Issue by EBoisseauSierra** [lod531/regPyHDFE#4]
Thanks for your work. I want to replicate the tutorial's example, using `regpyhdfe==0.0.10`. I've copied [the cleaned file](https://github.com/lod531/regPyHDFE/blob/main/data/cleaned_nlswork.dta) locally, and run:

```python
import pandas as pd

from regpyhdfe import Regpyhdfe

df = pd.read_stata('/path/to/cleaned_nlswork.dta')

target = "ln_wage"
predictors = ["hours", "tenure", "ttl_exp"]
absorb_ids = ["year", "idcode"]
cluster_ids = ["year"]

model = Regpyhdfe(df=df, target=target,
    predictors = predictors,
    absorb_ids=absorb_ids,
    cluster_ids=cluster_ids)

results = model.fit()
print(results.summary())
```

However, I get the following error:

```shell
$ python3.12 tutorial.py
B [[-0.00172073]
 [ 0.01088754]
 [ 0.03477828]]
 SE:
 [0.00051054 0.00282213 0.00274938]
T values [-3.37041781  3.85792197 12.64951351]
Traceback (most recent call last):
  File "/Users/ebosi/regpyhdfe/tutorial.py", line 18, in <module>
    print(results.summary())
          ^^^^^^^^^^^^^^^^^
  File "/Users/ebosi/regpyhdfe/venv/lib/python3.12/site-packages/regpyhdfe/regpyhdfe.py", line 107, in <lambda>
    self.res.summary = lambda yname=None, xname=None, title=None, alpha=.05:summary(self.res._results, self, yname=None, xname=None, title=None, alpha=.05)
                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ebosi/regpyhdfe/venv/lib/python3.12/site-packages/regpyhdfe/regpyhdfe.py", line 201, in summary
    t_interval = np.asarray(t.interval(alpha=(1-alpha), df=regpyhdfe.model.df_resid))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: rv_generic.interval() missing 1 required positional argument: 'confidence'
```

My virtual environment is defined as:

```shell
$ pip freeze
numpy==1.26.4
packaging==24.0
pandas==2.2.2
patsy==0.5.6
pyhdfe==0.2.0
python-dateutil==2.9.0.post0
pytz==2024.1
regpyhdfe==0.0.10
scipy==1.13.0
six==1.16.0
statsmodels==0.14.2
tzdata==2024.1
```

**Comment by lod531** [comment]
Hey, this is ancient so I can't be of much help, but this repo was actually deprecated in favour of 

https://github.com/lod531/FixedEffectModel

Everything this repo can do the other can do better, so I'd give that a shot

**Comment by EBoisseauSierra** [comment]
Thanks for your quick reply, I'll give it a look!
